# Generated by Django 5.2 on 2026-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
