# Generated by Django 5.2 on 2026-01-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0003_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='educationapp.schoolclass'),
        ),
    ]
