# Generated by Django 5.2 on 2026-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0004_student_class_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='enrolled_students', to='educationapp.course'),
        ),
    ]
